version: '3.3'

services:

  rest-api:
    image:
      rest-api-image
    build:
      context: .
      dockerfile: rest-api/Dockerfile
    container_name: rest-api-container
    networks:
      - cloud
    ports:
      - "80:8080"
    depends_on:
      - postgres
      - rabbitmq
      - redis
    environment:
      - "POSTGRES_URL=jdbc:postgresql://postgres:5432/javalab_exam"
      - "POSTGRES_USERNAME=postgres"
      - "POSTGRES_PASSWORD=gev56poison"
      - "RABBITMQ_HOST=rabbitmq"
      - "REDIS_HOST=redis"
    restart: on-failure

  pdf-generator:
    image:
      pdf-generator-image
    build:
      context: .
      dockerfile: pdf-generator/Dockerfile
    container_name: pdf-generator-container
    networks:
      - cloud
    ports:
      - "81:8080"
    depends_on:
      - rabbitmq
    environment:
#      - "AMQP_URL=amqp://rabbitmq?connection_attempts=5&retry_delay=5"
      - "RABBITMQ_HOST=rabbitmq"
    restart: on-failure

  postgres:
    image:
      postgres
    container_name: postgres
    networks:
      - cloud
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: javalab_exam
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: gev56poison
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - cloud
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672"]
      interval: 5s
      timeout: 15s
      retries: 1


  redis:
    image:
      bitnami/redis:latest
    container_name: redis
    networks:
      - cloud
    ports:
      - "6379:6379"
    volumes:
      - redis-volume:/data

volumes:
  pgdata:
  redis-volume:
networks:
  cloud:
    external: true