spring:
  redis:
    host: ${REDIS_HOST}
  rabbitmq:
    host: ${RABBITMQ_HOST}
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create

jwt.secret: javalab
