<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Title</title>
    <link rel="stylesheet" href="src/main/resources/static/style.css"/>
</head>
<body>
<section class="page">
    <div class="page__container">
        <div class="page__header">
            <div class="page__header--inner">
                Генеральному директору <br/>
                ООО
                «<span class="company__name">_______________</span>»
                <br/> от (должность) <br/>  ${name}
            </div>
        </div>
        <div class="page__name">заявление.</div>
        <div class="page__body">
            <p class="page__body--text">
                Прошу  уволить  меня  с  занимаемой должности
                «__» ___________ 20__
                года по  собственному  желанию  в  соответствии  пунктом  3  ст.  77  Трудового кодекса Российской Федерации.
            </p>
        </div>
        <div class="page__footer">
            <div class="page__footer--text">
                (должность) <br/> подпись, число.
            </div>
        </div>
    </div>
</section>
</body>
</html>