<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Title</title>
    <link rel="stylesheet" href="src/main/resources/static/style.css"/>
</head>
<body>
<section class="page">
    <div class="page__container">
        <div class="page__header">
            <div class="page__header--inner">
                Директору ООО «___________» <br/> ___________________________ <br/>  от ${name}
            </div>
        </div>
        <div class="page__name">ЗАЯВЛЕНИЕ</div>
        <div class="page__body">
            <p class="page__body--text">
                Прошу  предоставить  мне ежегодный  оплачиваемый  отпуск  с  «__» ___________ 20__года
                по «__» ___________ 20__года сроком  на __ календарных дней.
            </p>
        </div>
        <div class="page__footer">
           <div class="page__footer--date">Дата</div>
           <div class="page__footer--fio">Подпись, (ФИО) </div>
        </div>
    </div>
</section>
</body>
</html>